export const OPEN_NAVBAR_SAVE_CHANGE = "OPEN_NAVBAR_SAVE_CHANGE";
export const FETCH_LIST_FACEBOOK_PAGE = "FETCH_LIST_FACEBOOK_PAGE";
export const DELETE_FACEBOOK_PAGE = "DELETE_FACEBOOK_PAGE";
export const FETCH_LIST_FACEBOOK_PAGE_EVENTS = "FETCH_LIST_FACEBOOK_PAGE_EVENTS";